//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEEWiN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plan()
        {
            this.Plan_Order = new HashSet<Plan_Order>();
        }
    
        public string PId { get; set; }
        public string PType { get; set; }
        public string PName { get; set; }
        public decimal Rate { get; set; }
        public string Risk { get; set; }
        public string Tips { get; set; }
        public System.DateTime Open_Date { get; set; }
        public System.DateTime Close_Date { get; set; }
        public int Offering_Day { get; set; }
        public decimal PPrice { get; set; }
        public decimal Capital_Size { get; set; }
        public decimal Capital_Object { get; set; }
        public bool Plan_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_Order> Plan_Order { get; set; }
    }
}
