//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEEWiN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staking()
        {
            this.Staking_Order = new HashSet<Staking_Order>();
        }
    
        public string SId { get; set; }
        public string SType { get; set; }
        public string Symbol { get; set; }
        public string SName { get; set; }
        public decimal ARP { get; set; }
        public Nullable<System.DateTime> Open_Date { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public int Offering_Day { get; set; }
        public decimal SPrice { get; set; }
        public decimal Capital_Size { get; set; }
        public Nullable<decimal> Capital_Object { get; set; }
        public bool Staking_Status { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staking_Order> Staking_Order { get; set; }
    }
}
